// automatically generated by the FlatBuffers compiler, do not modify

package users

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserContainer struct {
	_tab flatbuffers.Table
}

func GetRootAsUserContainer(buf []byte, offset flatbuffers.UOffsetT) *UserContainer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserContainer{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *UserContainer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserContainer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UserContainer) ListOfUsers(obj *User, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *UserContainer) ListOfUsersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func UserContainerStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UserContainerAddListOfUsers(builder *flatbuffers.Builder, ListOfUsers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ListOfUsers), 0)
}
func UserContainerStartListOfUsersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func UserContainerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
