// automatically generated by the FlatBuffers compiler, do not modify

package articles

const (
	ContentUnionNONE = 0
	ContentUnionImageContent = 1
	ContentUnionParagraph = 2
)

var EnumNamesContentUnion = map[int]string{
	ContentUnionNONE:"NONE",
	ContentUnionImageContent:"ImageContent",
	ContentUnionParagraph:"Paragraph",
}

