// automatically generated by the FlatBuffers compiler, do not modify

package articles

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Image struct {
	_tab flatbuffers.Table
}

func GetRootAsImage(buf []byte, offset flatbuffers.UOffsetT) *Image {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Image{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Image) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Image) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Image) Url() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Image) Mime() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Image) Width() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Image) MutateWidth(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *Image) Height() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Image) MutateHeight(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func ImageStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ImageAddUrl(builder *flatbuffers.Builder, url flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(url), 0)
}
func ImageAddMime(builder *flatbuffers.Builder, mime flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(mime), 0)
}
func ImageAddWidth(builder *flatbuffers.Builder, width int32) {
	builder.PrependInt32Slot(2, width, 0)
}
func ImageAddHeight(builder *flatbuffers.Builder, height int32) {
	builder.PrependInt32Slot(3, height, 0)
}
func ImageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
