// automatically generated by the FlatBuffers compiler, do not modify

package articles

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Paragraph struct {
	_tab flatbuffers.Table
}

func GetRootAsParagraph(buf []byte, offset flatbuffers.UOffsetT) *Paragraph {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Paragraph{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Paragraph) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Paragraph) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Paragraph) Base(obj *Content) *Content {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Content)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Paragraph) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ParagraphStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ParagraphAddBase(builder *flatbuffers.Builder, base flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(base), 0)
}
func ParagraphAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(text), 0)
}
func ParagraphEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
